#!/usr/bin/env bash
# geoip-block.sh
# Downloads IP ranges for specified countries from ipdeny.com and
# generates iptables DROP rules, then writes them to /etc/iptables/rules.v4
#
# Usage:
#   COUNTRIES=ru,cn,in ./geoip-block.sh
#   or
#   ./geoip-block.sh ru cn in

set -euo pipefail

IPDENY_URL="https://www.ipdeny.com/ipblocks/data/aggregated"
RULES_FILE="/etc/iptables/rules.v4"
CHAIN="INPUT"

# ── resolve country list ──────────────────────────────────────────────────────
if [[ $# -gt 0 ]]; then
    # Accept space-separated args: ./script.sh ru cn in
    IFS=',' read -ra COUNTRY_LIST <<< "$(IFS=','; echo "$*")"
elif [[ -n "${COUNTRIES:-}" ]]; then
    # Accept comma-separated env var: COUNTRIES=ru,cn,in
    IFS=',' read -ra COUNTRY_LIST <<< "$COUNTRIES"
else
    echo "ERROR: No countries specified." >&2
    echo "Usage: COUNTRIES=ru,cn,in $0" >&2
    echo "  or:  $0 ru cn in" >&2
    exit 1
fi

# ── sanity checks ─────────────────────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (needed to write $RULES_FILE)." >&2
    exit 1
fi

command -v curl  >/dev/null 2>&1 || { echo "ERROR: curl is required." >&2; exit 1; }
command -v iptables >/dev/null 2>&1 || { echo "ERROR: iptables is required." >&2; exit 1; }

mkdir -p "$(dirname "$RULES_FILE")"

# ── download all zone files first ─────────────────────────────────────────────
declare -A ZONE_DATA   # country_code -> newline-separated CIDR list

for country in "${COUNTRY_LIST[@]}"; do
    country="${country,,}"   # lowercase
    url="${IPDENY_URL}/${country}-aggregated.zone"
    echo "Fetching ${url} ..."
    data=$(curl -fsSL --max-time 30 "$url") || {
        echo "ERROR: Failed to fetch zone for country '${country}' from ${url}" >&2
        exit 1
    }
    ZONE_DATA["$country"]="$data"
    count=$(echo "$data" | grep -c '^[0-9]' || true)
    echo "  -> ${count} CIDR blocks for ${country}"
done

# ── build rules.v4 content ────────────────────────────────────────────────────
echo "Building ${RULES_FILE} ..."

{
    echo "# Generated by geoip-block.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
    echo "# Blocked countries: ${COUNTRY_LIST[*]}"
    echo "*filter"
    echo ":INPUT ACCEPT [0:0]"
    echo ":FORWARD ACCEPT [0:0]"
    echo ":OUTPUT ACCEPT [0:0]"
    echo ""

    # One block per country for readability
    for country in "${COUNTRY_LIST[@]}"; do
        country="${country,,}"
        echo "# --- Block: ${country^^} ---"
        while IFS= read -r cidr; do
            # Skip blank lines and comments
            [[ -z "$cidr" || "$cidr" == \#* ]] && continue
            echo "-A ${CHAIN} -s ${cidr} -m comment --comment \"country-block:${country^^}\" -j DROP"
        done <<< "${ZONE_DATA[$country]}"
        echo ""
    done

    echo "COMMIT"
} > "$RULES_FILE"

echo "Written: ${RULES_FILE}"

# ── apply rules ───────────────────────────────────────────────────────────────
echo "Applying rules with iptables-restore ..."
iptables-restore < "$RULES_FILE"

echo "Restarting netfilter-persistent.service ..."
systemctl restart netfilter-persistent.service
echo "Done. Rules are active."
